input-output-hk/marconi

- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Node/Client/GenesisConfig.hs
- marconi-chain-index/test-compare-cardano-db-sync/Spec.hs
* Fixed readNetworkConfig to use the absolute path for the Conway genesis file.
* Fixed readConwayGenesis to render the NEConwayConfig error message instead of NEAlonzoConfig error message
* Re-grouped function in the `Marconi.ChainIndex.Node.Client.GenesisConfig` into something more cohesive.
- Branch
- PR
> Fixed error when reading Conway genesis config for the EpochState indexer

- marconi-core/test/Marconi/Core/Spec/Experiment.hs
It should fix a failure in the test that checks if the coordinator stops the indexers correctly in error that happen in CI when the Darwin cluster is overloaded
- Branch
- PR
> Wait longer before checking workers state in test

- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Orphans.hs
- marconi-chain-index/src/Marconi/ChainIndex/Types.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
[PLT-5574](https://input-output.atlassian.net/browse/PLT-5574): The UtxoByAddress response should include the block_index of the transaction
This is where cardano-db-sync does it: https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db-sync/src/Cardano/DbSync/Era/Byron/Insert.hs#L154 (added in [this PR](https://github.com/input-output-hk/cardano-db-sync/pull/94/files#diff-8c7f6315feb7f8370eaab00dca87e4abb2c56afda9e97d8796b8c47297c78378R123))
- Branch
- PR
> Add block index to utxo indexer

- marconi-sidechain/doc/adr/01-sdd-computation.adoc
Added an ADR describing the possible solutions for computing the SDD per epoch in `marconi-sidechain`.
The current implemented approach suffers from a large memory consumption because of the `LedgerState` computation which is used to extract the SDD.
We introduce different alternative solutions to the issue. All come with drawbacks. 
Hopefully, this will inform our decision on how to move forward.
Here is the rendered link of the document: https://github.com/input-output-hk/marconi/blob/PLT-5592-document-architectural-solutions-for-alternative-sdd-computation-for-marconi/marconi-sidechain/doc/adr/01-sdd-computation.adoc
> Add ADR for the computation of the SDD per epoch

- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/EpochState.hs
- marconi-chain-index/src/Marconi/ChainIndex/Utils.hs
* In the resumablePoints implementation, we now try to deserialize the LedgerState when identifying the possible resumable points from the LedgerStates saved on disk. If the file is not deserializable, we ignore it. Then, that LedgerState will get deleted in the `persistToStorage` implementation.
* Added a proper datatype (`LedgerStateFileMetadata`) for representing the metadata contained in the LedgerState filename.
* Tested on mainnet and preprod. Validated that when stopping `marconi-chain-index` when LedgerState is only partially written, it deletes it and resumes from the previous one.
- Branch
- PR
> PLT-41 Fixed resuming error in EpochState indexer when the LedgerState was partially written on disk.

- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/EpochState.hs
- marconi-chain-index/test-compare-cardano-db-sync/Spec.hs
Test a change to epoch state indexer.
There may have been an off-by-one error in how epoch number and stakepool sizes are matched up, but will shelve this, if this branch doesn't fix the issue.
- Branch
- PR
> Attempt get cardano-db-sync and Marconi have same output for epoch stakepool sizes (SDD)

- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
Reverting the SQL representation of UTXO to two tables (unspent/spent). Add an index on TxId/TxIx to speed up the queries.
- Branch
- PR
> PLT-6068 Improve Utxo indexer performance

- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-sidechain/README.md
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/MintBurn.hs
[PLT-5577](https://input-output.atlassian.net/browse/PLT-5577): MintBurn indexer: get only transactions that resulted in burning of tokens:
- Added queries to get only burn events
- Added test to query burns, both all of them and then pick a random one and query that
- Use the burn query in marconi-sidechains JSON-RPC API
- Added sample query and response to README (this appears to be the first burn on mainnet)
- Changed tests to generate both mint and burn (quantity < 0) events, all tests continue to pass (except endToEnd, there I suspect one can't burn more than has been minted, so generated events would have to take that into account) 
- Branch
- PR
> Add burn query to MintBurn indexer, query only burn in marconi-sidechain

- marconi-chain-index/src/Marconi/ChainIndex/Utils.hs
Changed querySecurityParam function so that it can query the security parameter before Babbage era (as it's currently hardcoded to Babbage).
- Branch
- PR
> Changed querySecurityParam function so that it can query the security parameter before Babbage

- marconi-chain-index/src/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-chain-index/src/Marconi/ChainIndex/Orphans.hs
- marconi-chain-index/src/Marconi/ChainIndex/Types.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/MintBurn.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/MintBurn.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Routes/Golden/address-utxo-response.json
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Routes/Golden/mintingpolicyhash-tx-response.json
- marconi-sidechain/test/Spec/Marconi/Sidechain/Routes.hs
Made the following adjustment to the getBurn query:
- Branch
- PR
> PLT-5578 Mintburn response

- marconi-chain-index/src/Marconi/ChainIndex/Indexers/EpochState.hs
- marconi-chain-index/test-compare-cardano-db-sync/Spec.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/EpochState.hs
- marconi-sidechain/doc/API.adoc
- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/EpochState.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Routes.hs
It was a trivial change. See the Note [Active stake pool delegation query] to understand the rationale of the implementation.
* Changed the EpochSDD query of the EpochState indexer to provide the *active* SDD.
* Refactored a bit the db-sync comparison test
* Changed the EpochSDD query of db-sync to match the change in the EpochState indexer.
- Branch
- PR
> Changed the query in EpochState to query for the active SDD of an epoch

- marconi-chain-index/json-rpc/src/Network/JsonRpc/Server/Types.hs
- marconi-chain-index/json-rpc/src/Network/JsonRpc/Types.hs
- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Orphans.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
- marconi-sidechain/README.md
- marconi-sidechain/doc/API.adoc
- marconi-sidechain/marconi-sidechain.cabal
- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/MintBurn.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Types.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/MintBurn.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Routes/Golden/address-utxo-response.json
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Routes/Golden/current-synced-point-response-2.json
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Routes/Golden/mintingpolicyhash-tx-response.json
- marconi-sidechain/test/Spec/Marconi/Sidechain/Routes.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/RpcClientAction.hs
Updated the JSON-RPC request and response interface of `marconi-sidechain` to reflect the specification in API.adoc.
* Added indexing of `BlockNo` in the AddressUtxo indexer
* Renamed the `blockHash` field in the AddressUtxo table to `blockHeaderHash` instead in order to be more explicit.
* Modified the `LastSyncQuery` to `LastSyncedBlockInfoQuery` which returns a `BlockInfo` type instead of `ChainPoint`.
* Fixed bug when starting `marconi-sidechain` and trying to query the MintBurn indexer before the indexer was able to index some information. In that scenario, the indexer didn't have time to be created, thus we got returned a query error. Instead of a query error, we just return an empty result.
* Updated the `marconi-sidechain` with up-to-date examples.
* Updated the …
> PLT-5770 Updated the JSON-RPC request and response interface of `marconi-sidechain` to reflect the specification in API.adoc.

- marconi-chain-index/app/Main.hs
- marconi-chain-index/bench/BenchQueries.hs
- marconi-chain-index/src/Marconi/ChainIndex/CLI.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Types.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/Utxo/UtxoIndex.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Types.hs
- marconi-sidechain/src/Marconi/Sidechain/Bootstrap.hs
- marconi-sidechain/src/Marconi/Sidechain/CLI.hs
Add CLI parameter to the Utxo indexer  to optionally enabling persisting the  ReferenceScript, inlineScript and the corresponding hash in the Utxo SQLite table, unspentTransactions.
- For sidechain, this parameter will be set to `False` indicating we do not save ReferenceSctips.
- For marconi-chain-index, this parameter by default is set to Enabled, saving the ReferenceScript. Users may turn it off using CLI parameter.  
For additional detail, see [PLT-5571](https://input-output.atlassian.net/browse/PLT-5571)
- Branch
- PR
> Utxo-Indexer optionally stores Reference script

- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/Utxo/UtxoIndex.hs
- marconi-core/src/Marconi/Core/Experiment.hs
- marconi-core/src/Marconi/Core/Experiment/Class.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/ListIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/MixedIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/SQLiteIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Query.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/IndexWrapper.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithAggregate.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithAggregation.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithCache.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithDelay.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithTransform.hs
- marconi-core/src/Marconi/Core/Experiment/Type.hs
- marconi-core/src/Marconi/Core/Experiment/Worker.hs
- marconi-core/test/Marconi/Core/Spec/Experiment.hs
`TimedEvent` is great to attach a chainPoint to a datatype, it was hard to manipulate though, because each type should have a `Point` type instance to use it, and we couldn't map on it because of the type family.
- Change `TimedEvent event` to `TimedEvent point event`.
- Add `Functor`, `Foldable` and `Traverse` to the experimental indexer.
- Refactor code to take advantage of it
- Branch
- PR
> Reduce the need of `Point` type family

- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/EpochState.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/EpochState.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/MintBurn.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
- marconi-sidechain/src/Marconi/Sidechain/Bootstrap.hs
With tryReadTMVar, if the read failed because the indexer was not available yet, it would return an empty result. Now, with readTMVar, it restarts until the indexer is available after the write action has finished.
Doing so, we also needed to make sure that each indexer worker calls the callback when the indexer is initially created.
- Branch
- PR
> Replace tryReadTMVar with readTMVar when querying the indexers in marconi-sidechain.

- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
In the UtxoEvent, we used to have `ChainPoint` which could be `ChainPointAtGenesis`. However, it should be impossible to create an event which is at genesis. Therefore, we can just use `BlockInfo` instead which contains additional info such as `BlockNo`, `BlockTimestamp` and `EpochNo`. 
This change also means that we don't need to handle the `Genesis` case in most of the code, thus we gain some nice refactoring.
@berewt Part I've contemplated is if we should put the `BlockInfo` in a separate table, and then the `utxo` table and the `spent` table would point to the correct row in the `BlockInfo` table. Thoughts?
- Branch
- PR
> Replaced ChainPoint in UtxoEvent with BlockInfo

- marconi-chain-index/src/Marconi/ChainIndex/CLI.hs
- marconi-chain-index/test/Spec/Golden/Cli/marconi-chain-index___disable_address_data.help
- marconi-chain-index/test/Spec/Golden/Cli/marconi-chain-index___help.help
The optional storage of utxo introduced a flag and disabled another one, but didn't modify the CLI parsing accordingly.
As a consequence, we were assigning the wrong options during the parsing.
It's fixed.
- Branch
- PR
> Bugfix CLI parsing

- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
The logic that allows the deserialisation of a list of TxIn when we're retrieving utxos at a given address didn't cover the case of txout without any inputs, leading to a deserialisation error. It's now fixed.
It led us to another bug, as Utxo should have an input. The reason is that we were filtering out an utxo and its corresponding spent if they occurred in the same block. It was a bad behaviour as we lost track of inputs.
As a consequence:
- we remove when we compose `TxOutBalance`.
- There is no longer any reason to store utxo as a Set, as no set operations were required anymore, we move back to a list.
- Branch
- PR
> PLT-6440 Deserialisation of txInputs doesn't fail when no inputs were found

- marconi-chain-index/bench/BenchQueries.hs
- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/AddressDatum.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/EpochState.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/LastSync.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/ScriptTx.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Coordinator.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
This PR has introduce two new features:
- We now wait for each indexer to process their block before exiting Marconi. The wait has a 3 minutes timeout.
- We keep track of all the chainpoints when we flush on disk. I wanted to keep only one event first, but as we flush the whole memory at the moment and as we want to be able to resume from at least 1 non volatile point, I had to do so.
This PR doesn't revert the intersection computation. It should be done if we want to continue with this indexer design.
It isn't a problem for side chain as the epoch state indexer will lag behind anyhow and will be the one that will be used when resuming.
- Branch
- PR
> Clean exit and better resume points

- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
This PR address an performance issue raised by @james-iohk on the query to the utxo indexer:
since we add the inputs to the result of the query, we need to join on the `spentTxId` field of the `spent` table. The table is huge and without an index, it was way too slow. 
- Branch
- PR
> Add a missing index to speed up the utxo query

- nix/per-system-outputs.nix
create an alias for the `marconi-sidechain` excutalbe.
The test:
```
nix build .#marconi-sidechain
cd result/bin
./marconi-sidechain --help
```
- Branch
- PR
> Create alias for marconi-sidechain-exe

- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
The `getLastSyncPoint` endpoint relied on the `unspent_utxo` table, and so could return invalid information.
This PR:
- introduced a specific `blockInfo` table,
- rely on it to get the last sync point,
- use this table to remove the block info data duplication in the `spent` and `unspent_utxo` tables.
- Branch
- PR
> Fix the lastSync endpoint

- marconi-sidechain/doc/API.adoc
- marconi-sidechain/examples/json-rpc-client/src/Main.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Routes.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/RpcClientAction.hs
Add better error messages to the GetUtxoByAddress endpoint, as defined in the API specification document.
I decided to drop the error message for a `createBeforeSlotNo` that is after the `getCurrentSyncPoint` slot, to avoid an extra query to resolve the query.
- Branch
- PR
> Clearer JSON-RPC error message for the GetUtxo endpoint

- marconi-chain-index/app/Main.hs
- marconi-chain-index/bench/BenchQueries.hs
- marconi-chain-index/src/Marconi/ChainIndex/CLI.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Logging.hs
- marconi-chain-index/src/Marconi/ChainIndex/Types.hs
- marconi-chain-index/test/Spec/Golden/Cli/marconi-chain-index___disable_address_data.help
- marconi-chain-index/test/Spec/Golden/Cli/marconi-chain-index___help.help
- marconi-sidechain/src/Marconi/Sidechain/Api/Types.hs
- marconi-sidechain/src/Marconi/Sidechain/Bootstrap.hs
- marconi-sidechain/src/Marconi/Sidechain/CLI.hs
- marconi-sidechain/test/Spec/Golden/Cli/marconi-sidechain___help.help
- marconi-sidechain/test/Spec/Golden/Cli/marconi-sidechain___socket.help
Added CLI options to fail if one indexer is forced to resync from genesis and log resumable points of each indexer
Here are some examples on marconi-sidechain.
__When resuming from non-genesis resumable points__
```
[marconi-sidechain:Info:9] [2023-07-25 17:11:30.26 UTC] Resumable points for each indexer:
[ ChainPoint(Slot 32262079, BlockHash 5bc7a83aa740515a7cf1fcf510e6d8778d23fd62e999b31b380f9cc7548db79b)
, ChainPoint(Slot 32054455, BlockHash 8b70cd587d802a596a8dd2c58543f37510ddcf2b14fb7869550561ea91c12b0f)
, ChainPoint(Slot 32262079, BlockHash 5bc7a83aa740515a7cf1fcf510e6d8778d23fd62e999b31b380f9cc7548db79b) ]
[marconi-sidechain:Info:9] [2023-07-25 17:11:30.27 UTC] Starting from ChainPoint(Slot 32054455, BlockHash 8b70cd587d802a596a8dd2c58543f37510ddcf2b14fb7869550561ea91c12b0f). …
```
> PLT-6751 Added CLI options to fail if one indexer is forced to resync from genesis

- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-core/marconi-core.cabal
- marconi-core/src/Marconi/Core/Experiment.hs
- marconi-core/src/Marconi/Core/Experiment/Class.hs
- marconi-core/src/Marconi/Core/Experiment/Coordinator.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/LastPointIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/IndexWrapper.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithCatchup.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithDelay.hs
- marconi-core/test/Marconi/Core/Spec/Experiment.hs
- marconi-core/test/Spec.hs
As we want to move towards full in-database indexers, we discussed the need to have a way to batch events to the database until we catchup with the tip.
This PR proposes a indexer transformer that does exactly this: when an block comes in, we compute the distance to the tip and we decide either:
- that we are too far from the tip and thus we put the block in a batch and if the batch is full, we send it to the database
- that we are close enough to the tip, we just skip the batch mechanism and add directly the block to the indexer.
- Branch
- PR
> Add a catch-up mechanism at an indexer transformer

- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/AddressDatum.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/EpochState.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/LastSync.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/ScriptTx.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintBurn.hs
* Added BEGIN and COMMIT SQL statements when doing bulk inserts in MintBurn. Went from ~200blocks/s to ~3000blocks/s in the first few epochs.
* Removed unused functions in MintBurn indexer
* MintBurn.toUpdate now returns StorableEvent instead of TxMints
- Branch
- PR
> Significant speed increase on the MintBurn indexer (plus some small refactoring)

- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
Fix UTXO bug and modify the existing tests to catch regression
- Branch
- PR
> PLT-6881 Utxo indexer returns all spent transaction outputs when not specifying `unspentBeforeSlotNo` field

- marconi-chain-index/src/Marconi/ChainIndex/Indexers/EpochState.hs
The epochState indexer has a nested transactions issue after the performance PR. Remove the extra BEGIN statement.
- Branch
- PR
> Fix nested transaction issue

- cardano-streaming/src/Cardano/Streaming.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-sidechain/app/Main.hs
When the eraHistory used to compute the epochNo was outdated, the stream was blocking when it was trying to update it because it was updating a full `MVar`.
The refactoring remove the need of the `MVar`.
It also improves the robustness of the concurrent code of the indexers and some extra logging, integrated during the bug investigation.
- Branch
- PR
> PLT-969 Resolve bug in Cardano streaming, blocking on new era

- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/Utxo/UtxoIndex.hs
- marconi-core/src/Marconi/Core/Experiment.hs
- marconi-core/src/Marconi/Core/Experiment/Class.hs
- marconi-core/src/Marconi/Core/Experiment/Coordinator.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/LastPointIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/ListIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/MixedIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/SQLiteIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/IndexWrapper.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithAggregate.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithCache.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithCatchup.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithDelay.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithPruning.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithTracer.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithTransform.hs
- marconi-core/src/Marconi/Core/Experiment/Worker.hs
- marconi-core/test/Marconi/Core/Spec/Experiment.hs
- marconi-tutorial/src/Marconi/Tutorial/Indexers/AddressCount.hs
- marconi-tutorial/test/Spec/Marconi/Tutorial/AddressCount.hs
Remove the `Rollbackable` typeclass, moving the `rollback method to `IsIndex`.
Add a few rules to the `IsIndex` typeclass.
- Branch
- PR
> Remove the `Rollbackable` typeclass

- marconi-core/src/Marconi/Core/Experiment/Indexer/SQLiteIndexer.hs
- marconi-core/test/Marconi/Core/Spec/Experiment.hs
The from genesis query was wrong. It's fixed, the indexer that tests the rollback is fixed as well, to cover the case.
- Branch
- PR
> Fix new rollback

- marconi-chain-index/json-rpc/src/Network/JsonRpc/Server/Types.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Orphans.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Routes/Golden/current-synced-point-response-1.json
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Routes/Golden/current-synced-point-response-2.json
- marconi-sidechain/test/Spec/Marconi/Sidechain/Routes.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/RpcClientAction.hs
Added the chain tip to the event and propagated it down to the side chain query.
The only issue (that would be complex to overcome) is that we ignore chainTip on rollback.
Handling it means either adding an indexing call on rollback and changing the event type to allow it, or adding a specific backdoor function to change the content of the tip. 
These solutions look ugly so I didn't integrate it. May be there is a cleaner one but I hadn't find it.
- Branch
- PR
> PLT-6892 Add node tip info to the getLastSyncedBlock query

- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/SyncHelper.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/SQLiteIndexer.hs
There was an off by 1 error that ends in retrieving 2 points instead of 1 in the getLastSync query, stopping the application on resuming.
- Branch
- PR
> Fix syncLastPointQuery

- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Coordinator.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers.hs
- marconi-core/src/Marconi/Core/Experiment.hs
- marconi-core/src/Marconi/Core/Experiment/Coordinator.hs
- marconi-core/test/Marconi/Core/Spec/Experiment.hs
The coordinator compute its `lastSyncPoint` through the workers instead of maintaining it in its own variable.
It should improve the accuracy of the last sync point when some transformer changes the behaviour of the indexing.
- Branch
- PR
> Change lastSyncPoint in coordinator

- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/BlockInfo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Datum.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Spent.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/SyncHelper.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-core/src/Marconi/Core/Experiment.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/SQLiteIndexer.hs
- marconi-core/test/Marconi/Core/Spec/Experiment.hs
- marconi-tutorial/src/Marconi/Tutorial/Indexers/AddressCount.hs
The experimental indexer design originally expect the SQL database to track only stable blocks. As a consequence, it didn't store anything if there was no event in the block.
As we now want to store unstable events as well, we need to keep track of how far we indexed, and thus to store the sync point, even if no relevant event were introduced. This PR modify the `SQLiteIndexer` to allow this.
It introduces an extra query in the indexer to store the `Point` of the `TimedEvent`, that is triggered independently of the event content. The query is optional though, as some indexers may already have the corresponding information in their event (as for the `BlockInfo` indexer).
All the indexers are modified accordingly.
- Branch
- PR
> Always track point

- marconi-chain-index/json-rpc/src/Network/JsonRpc/Types.hs
- marconi-sidechain/doc/API.adoc
- marconi-sidechain/examples/json-rpc-client/src/Main.hs
- marconi-sidechain/examples/run-pre-prod-queries
- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/RpcClientAction.hs
* `getCurrentSyncedBlock` method
* `getTargetAddresses` method
* Update documentation
* Improve error reporting in `marconi-sidechain/examples/run-pre-prod-queries`
Note that we allow `params` to be empty but not missing, because we don't want `params` to be optional for other methods and they all share a common `Request p` datatype.
- Branch
- PR
> PLT-6832 Allow params to be empty for some JSON-RPC methods

- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Runner.hs
It's weird that `marconi-chain-index-experimental` was still working without this fix: we didn't start the chain sync protocol in a dedicated thread and thus this was blocking the indexing.
- Branch
- PR
> Start the chainSync protocol in a dedicated thread

- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/EpochState.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Worker.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Run.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Runner.hs
- marconi-core/marconi-core.cabal
- marconi-core/src/Marconi/Core/Experiment.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/FileIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/MixedIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/SQLiteIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Query.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/Class.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/IndexTransformer.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithCache.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithCatchup.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithDelay.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithFold.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithPruning.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithResume.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithTracer.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithTransform.hs
- marconi-core/src/Marconi/Core/Experiment/Worker.hs
- marconi-core/test/Marconi/Core/Spec/Experiment.hs
The performance isn't good. From the various tests, it seems that the main issue is the ledger state computation but it doesn't explain why it's slower than the original experimentation.
Missing features:
- tests
- queries
Issues:
- resuming doesn't work when the indexer is ahead of the other indexers
- performance
Why do we propose it then?
Once these points are covered, we should be able to have a better alternative than the current epoch state, especially once synced:
- we store only new blocks, not epoch-state, after each block
- we've decomposed the monolithic indexer into smaller parts.
- Branch
- PR
> Epoch state for the new indexer

- marconi-sidechain/examples/run-pre-prod-queries
- marconi-sidechain/marconi-sidechain.cabal
- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
Tested by running `marconi-sidechain/examples/run-pre-prod-queries` with an invalid slot number in `getBurnTokenEvents`.
```
getBurnTokenEvents({
"policyId": "00000000000000000000000000000000000000000000000000000000",
"createdBeforeSlotNo": 1000000
}) =
curl: (22) The requested URL returned error: 500
{
"error": {
"code": -32603,
"data": null,
"message": "Internal error"
},
"id": null,
"jsonrpc": "2.0"
}
```
- Branch
- PR
> PLT-7542 Catch exceptions in http handlers and return a JSON-RPC error

- marconi-chain-index/cardano-api-extended/src/Cardano/Api/Extended/Gen.hs
- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs
Creates a `genTxId` in `cardano-api-extended` as drop-in replacement for the same generator from `cardano-api`, which is degenerate. This allows us to generate `TxId` values reasonably expected to be unique across events in samples. Intended as a temporary replacement.
- Branch
- PR
> PLT-7842 temporary non-degenerate genTxId

- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/EpochState.hs
- Add the blockHeaderHash to the table (it was used in the query but not included).
- Makes the queryable instances more flexible.
- Branch
- PR
> Fixes for the epochState indexer

- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs
- marconi-core/src/Marconi/Core/Type.hs
* Add fields corresponding to `beforeSlotNo` and `afterTx` from the marconi-sidechain JSON RPC endpoint for burn token events to the `QueryByAssetId` type of `marconi-chain-index`.
* Modify the logic of both the list and SQLite indexer instances of `Queryable` for `MintTokenBlockEvents`, to consume the two new parameters and apply them to the query.
* Add a variant `SlotNoBoundsInvalid` to `QueryError` of `marconi-core`, which will be thrown from the updated query routines if either:
* The lower-bound slot number associated with `afterTx` is greater than the upper bound `beforeSlotNo` (or the requested query point),
* The upper-bound slot number `beforeSlotNo` is greater than the requested query point.
* Update the `QueryByAssetId` configuration type to be a record with lenses.
Pre-submit …
> PLT-7739 Add missing parameters to mint burn indexer

- marconi-chain-index/src/Marconi/ChainIndex/Error.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-sidechain/marconi-sidechain.cabal
- marconi-sidechain/src/Marconi/Sidechain/Concurrency.hs
- marconi-sidechain/src/Marconi/Sidechain/Error.hs
- marconi-sidechain/src/Marconi/Sidechain/Run.hs
When the program is closed with SIGINT or SIGTERM, we will now alter the exit code based on whether or not any indexers experience a timeout during shutdown.
I've added generalised machinery to both make these changes easier to read and to allow us to possibly re-use it, if necessary. If we do want to re-use it, we'd most likely want to move it (specifically `Concurrency.hs`) to a different file.
Additionally, this ONLY works _after_ a SIGINT or SIGTERM has been received. It feels like stepping outside the realms of that is going out of scope, because I think there's potentially a bunch more machinery that'll be needed for general exception handling (in the context of remapping exit codes).
- Branch
- PR
> PLT-7045 - Marconi sidechain exit codes during SIGINT or SIGTERM

- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Run.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs
* Adds support in the "experimental" indexers for filtering a `MintToken` event indexer by `PolicyId` and (maybe) `AssetName`. Previously, both were required as part of a filter on `AssetId` s. Such functionality is supported in the CLI and in the "legacy" indexers.
* Change `MintTokenEventConfig` type to match the CLI input type and to support the new functionality.
Note this intentionally does not fix a known bug (PLT-7793), which can be fixed easily if this PR is merged.
- Branch
- PR
> PLT-7885 support filtering mint token events by policyid

- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Logger.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Run.hs
There was a race condition between the mapping of errors returned by `buildIndexers` to `Text` and the exiting of the program with a failure condition. 
~I've resolved it by strictly evaluating the mapping.~
I've resolved it by using the `shutdown` function from `Cardano.BM`. This tells the logger to shutdown, and also waits for the shutdown to complete. The shutdown involves draining the queue, guaranteeing our message is processed.
Also, I'm now checking if the specified JSON file exists at the top level before continuing, which isn't strictly necessary as a part of this ticket now that I've fixed the root cause, but it makes sense so I'm leaving it in.
- Branch
- PR
> PLT-7794 - Check if file exists and strictly evaluate error textification

- marconi-chain-index/cardano-api-extended/src/Cardano/Api/Extended/Block.hs
- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/ChainTip.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Coordinator.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Run.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Runner.hs
- marconi-chain-index/src/Marconi/ChainIndex/Orphans.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Mockchain.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/BlockInfo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/ChainTip.hs
- marconi-core/marconi-core.cabal
- marconi-core/src/Marconi/Core.hs
- marconi-core/src/Marconi/Core/Indexer/FileIndexer.hs
- marconi-core/src/Marconi/Core/Indexer/LastEventIndexer.hs
- marconi-core/src/Marconi/Core/Query.hs
- marconi-tutorial/src/Marconi/Tutorial/Indexers.hs
- marconi-tutorial/src/Marconi/Tutorial/Indexers/AddressCount.hs
- The processing of the chain-sync events is modified to issue some events with the chain tip.
- We introduce the `LastEventIndexer`, an indexer that saves the last value of an event on disk, to use it to save chain tips.
- We modify the indexers organisation accordingly.
- Branch
- PR
> PLT-7932 Add tracking of the chain tip

- nix/project.nix
This was working already in `marconi-chain-index`.
Tested as follows:
```shellsession
$ for EXE in marconi-{sidechain,chain-index{-experimental,}}; do
>   $(nix build --quiet --no-link --print-out-paths .#$EXE)/bin/$EXE --version
> done
1.2.0.0-8968b7e6df657be5cd23677296d8dd4ffa852294
[marconi-sidechain:Info:27] [2023-10-13 22:31:40.68 UTC] marconi-sidechain-1.2.0.0-8968b7e6df657be5cd23677296d8dd4ffa852294
1.2.0.0-8968b7e6df657be5cd23677296d8dd4ffa852294
[marconi-chain-index-experimental:Info:29] [2023-10-13 22:31:40.82 UTC] marconi-chain-index-experimental-1.2.0.0-8968b7e6df657be5cd23677296d8dd4ffa852294
1.2.0.0-8968b7e6df657be5cd23677296d8dd4ffa852294
[marconi-chain-index:Info:27] [2023-10-13 22:31:40.97 UTC] marconi-chain-index-1.2.0.0-8968b7e6df657be5cd23677296d8dd4ffa852294
``` …
> PLT-7132 Fix git revision in marconi-sidechain and marconi-chain-index-experimental

- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/MintBurn.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
The `getBurnTokenEvents` RPC from `marconi-sidechain` was producing an internal error when an invalid slot number was given (eg because it's ahead of what the UTXO indexer has seen). This is because the `queryBlockNoAtSlotNo` function was throwing an exception.
Adding a test for this specific case seemed unwarranted, so I tested it using (a modified version of) `marconi-sidechain/examples/run-pre-prod-queries`:
```
getBurnTokenEvents({
"policyId": "00000000000000000000000000000000000000000000000000000000",
"createdBeforeSlotNo": 1000000
}) =
{
"error": {
"code": -32602,
"data": "Slot number doesn't exist yet",
"message": "Invalid params"
},
"id": 1,
"jsonrpc": "2.0"
}
```
- Branch
- PR
> PLT-7542 Improve error handling in `queryBlockNoAtSlotNo`

- marconi-sidechain-node/flake.lock
- marconi-sidechain-node/nix/project.nix
I recreated `flake.lock` by copying the one from `marconi` and running `nix flake lock --update-input cardano-node`. There were still errors when running `nix build .#hydraJobs.x86_64-linux.required` so I made some small changes to `nix/project.nix`.
Now `nix develop` doesn't try to build `ghc`, and `cabal build all` works without recompiling an unreasonable number of dependencies.
- Branch
- PR
> PLT-7795 Fix nix files in marconi-sidechain-node

- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Api/JsonRpc/Endpoint/CurrentSyncedBlock.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Api/JsonRpc/Endpoint/CurrentSyncedBlock/Tip.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Api/JsonRpc/Routes.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Api/JsonRpc/Server.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/BlockInfo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/ChainTip.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/CurrentSyncPointQuery.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/UtxoQuery.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/BlockInfo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-core/src/Marconi/Core/Indexer/LastEventIndexer.hs
Adding it required to correct a bug in the LastEvent indexer, to only track non-empty events.
- Branch
- PR
> PLT-7723 Add a CurrentSyncedBlock JSON-RPC endpoint

- .github/workflows/haddock.yml
- README.adoc
I've added a workflow which pushes builds Haddock documentation and pushes to the `gh-pages` branch. Combined with the configuration I've added to our repo settings, we'll now have Haddock sites deploy to: 
- https://input-output-hk.github.io/marconi/main/marconi-core
- https://input-output-hk.github.io/marconi/main/marconi-chain-index
- https://input-output-hk.github.io/marconi/main/marconi-core-json-rpc
- Branch
- PR
> PLT-5743 - Deploy Haddock GitHub page

- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/UtxoQuery.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/UtxoQuery.hs
Modified the type of the indexer used in the UTXO query so that we log any errors raised in the MonadError context.
Note: There isn't a straightforward way to test this, since we don't seem to be using the instance anywhere. Are we going to add an endpoint which calls this instance in the future?
- Branch
- PR
> PLT-8326 - Added WithTrace to UtxoQueryIndexer

- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
Modified the type of the indexer used in the current sync point query so that we log any errors raised in the `MonadError` context.
- Branch
- PR
> PLT-8321 - Added WithTrace to the indexer used for the current sync point query

- STYLEGUIDE.adoc
- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/test-lib/Test/Gen/Marconi/ChainIndex/MintTokenEvent.hs
- marconi-chain-index/test-lib/Test/Gen/Marconi/ChainIndex/Mockchain.hs
- marconi-chain-index/test-lib/Test/Gen/Marconi/ChainIndex/Types.hs
- marconi-chain-index/test-lib/Test/Helpers.hs
- marconi-chain-index/test-lib/Test/Integration.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Api/Gen.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/BlockInfo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/ChainTip.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Datum.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintTokenEvent.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Spent.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/UtxoQuery.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Orphans.hs
- marconi-starter/test/Spec/Marconi/Starter/AddressCount.hs
Adds some end-to-end tests using cardano-node-emulator for simple queries of marconi-chain-index:
* BlockInfo indexer
* MintTokenEvent indexer
To support that, it
* Changes the module structure of test-lib slightly for better organization
* Splits unit and property tests (both run via hedgehog), to avoid unintentionally overriding the 'propertyOnce' configuration for the unit tests.
* Suppresses 'SlotAdd' logging information from the node emulator to avoid polluting test output.
- Branch
- PR
> PLT-8098 new mintburn indexers e2e tests

- CONTRIBUTING.adoc
- doc/read-the-docs-site/README.md
- flake.lock
Instructions on how to install & upgrade nix and how to setup the binary caches are now included in the [relevant section](https://github.com/input-output-hk/iogx/blob/main/doc/api.md#flakenix) of the IOGX manual. 
This PR updates various files and documents that reference nix.
> Update nix documentation the README

- nix/project.nix
It's been failing randomly but frequently with a segfault recently, and in any case we don't need to check that it builds on Darwin since the copy that's deployed to the site will always be built on Linux.
> Disable the read-the-docs nix build on Darwin

- cabal.project
- marconi-sidechain/README.md
- nix/project.nix
* Update Nix prerequisites
* Put Nix first
* Add Docker instructions
* Mention `marconi-sidechain/examples/run-pre-prod-queries` for testing RPC
* Mention that Nix works on Mac
> Improve build and test instructions in marconi-sidechain README

- cabal.project
- nix/project.nix
It's been failing in CI with a segfault on Darwin for some time now even though it builds successfully on Linux. This is almost certainly a GHC bug. Ideally we would ensure that this example builds on all platforms, but we don't have time to investigate this GHC bug at the moment. Hopefully it will go away when we upgrade to a later version of GHC.
> Disable the `marconi-doc` Haskell example on Darwin

- .github/workflows/haddock.yml
The problem was: 
`Error: cabal: Failed to build documentation for plutus-script-utils-1.2.0.0
(which is required by lib:marconi-chain-index-test-lib from
marconi-chain-index-1.2.0.0).`
I've specified `marconi-chain-index:lib:marconi-chain-index` because that's all we care about here I believe, but I'm still a bit unsure as to why docs would fail to build for `plutus-script-utils`.
Note that I've not actually tested this end-to-end as it's a bit awkward and I'm essentially certain this'll work (and if it doesn't, it won't harm anything since it's already broken). The part I tested was that `cabal haddock marconi-chain-index` fails, and `cabal haddock marconi-chain-index:lib:marconi-chain-index` succeeds.
- Branch
- PR
> PLT-8794 - Specified marconi-chain-index:lib to avoid pulling in tests

- marconi-cardano-core/src/Marconi/Cardano/Core/Transformer/WithSyncStats/Backend/Prometheus.hs
I've used `addGauge` instead of `setGauge`, which will accumulate rather than overwrite.
- Branch
- PR
> PLT-8769 - Add, rather than overwrite the current metrics

- marconi-chain-index/src/Marconi/ChainIndex/CLI.hs
- marconi-chain-index/test/Spec.hs
- marconi-chain-index/test/Spec/Golden/Cli/marconi-chain-index___help.help
- marconi-sidechain-experimental/test/Spec/Golden/Cli/marconi-sidechain___help.help
- marconi-sidechain/test/Spec.hs
New log output:
```
$ cabal run marconi-sidechain-experimental:exe:marconi-sidechain-experimental -- --testnet-magic 1 -s test.socket -d test --node-config-path faef
[marconi-sidechain-experimental:Info:19] [2023-11-28 15:44:00.03 UTC] marconi-sidechain-1.2.0.0-544bba08c5075a7b68f784b980bdfc9960f520ac
[marconi-sidechain-experimental:Info:19] [2023-11-28 15:44:00.03 UTC] CliArgs
{ socketFilePath = "test.socket"
, nodeConfigPath = "faef"
, dbDir = "test"
, httpPort = 3000
, networkId = Testnet
( NetworkMagic
{ unNetworkMagic = 1 }
)
, targetAddresses = Nothing
, targetAssets = Nothing
, optionsRetryConfig = RetryConfig
{ baseTimeBeforeNextRetry = 1
, maybeMaxWaitTime = Just 1800
}
, optionsChainPoint = StartFromLastSyncPoint
}
[marconi-sidechain-experimental:Warning:19] [2023-11-28 …
```
> Changed first retry time to 1s

- doc/read-the-docs-site/marconi-doc.cabal
- legacy/marconi-chain-index-legacy/marconi-chain-index-legacy.cabal
- legacy/marconi-core-legacy/marconi-core-legacy.cabal
- marconi-cardano-core/marconi-cardano-core.cabal
- marconi-cardano-indexers/marconi-cardano-indexers.cabal
- marconi-chain-index/marconi-chain-index.cabal
- marconi-core-json-rpc/marconi-core-json-rpc.cabal
- marconi-core/marconi-core.cabal
- marconi-sidechain-experimental/marconi-sidechain-experimental.cabal
- marconi-sidechain/marconi-sidechain.cabal
- marconi-starter/marconi-starter.cabal
I did this while trying to fix dependency problems in `marconi-sidechain-node` but I thought it was worth keeping anyway.
[Since 3.4](https://cabal.readthedocs.io/en/stable/file-format-changelog.html#cabal-version-3-4) the file format requires that sublibraries be fully qualified even in the project they're defined in, just like they have to be in other other projects.
There's no particular connection between the version of cabal you're using and the file format version, other than cabal has to be newer than the file format. We're using cabal 3.10.
> Upgrade cabal files to 3.8

- nix/project.nix
This also removes a nix dependency on the source package
The var was being used by some commented-out tests that needed access to the node config. In the unlikely event that those tests are reinstated (they're more likely to be migrated to using the node emulator) we can have them use the solution that Brendan has just introduced for his recent PR (#266).
> Remove unused env var from marconi-chain-index.preCheck

- marconi-cardano-indexers/src/Marconi/Cardano/Indexers/ExtLedgerStateCoordinator.hs
- marconi-chain-index/src/Marconi/ChainIndex/Run.hs
Two main fixes and a change.
Fixes:
- Stop relying on asynchronous saves of the ledger, as it leads to the accumulation of ledger states in memory
- Save correctly the volatile blocks 
Change:
- Catchup now stops when we reach volatile events.
- Branch
- PR
> Fix rollbacks and memory issues due to accumulation of ExtLedgerStates

- cabal.project
This fixes recent CI failures in the GitHub workflow that builds haddocks
> Update source-dep commit for quickcheck-contractmodel

- marconi-core/marconi-core.cabal
- marconi-core/test/Marconi/CoreSpec.hs
An attempt at fixing an unstable test on Darwin, using Neil's suggestion in https://input-output.atlassian.net/browse/PLT-8932
- Branch
- PR
> PLT-8932 - Darwin test instability fix attempt

- marconi-cardano-indexers/src/Marconi/Cardano/Indexers/UtxoQuery.hs
- marconi-cardano-indexers/test/Spec/Marconi/Cardano/Indexers/UtxoQuery.hs
Fixes a typo in the `UtxoQuery` aggregate's `Queryable` instance, whose SQL statement contained an alias that did not exist.
- Branch
- PR
> PLT-8935 Typo in UtxoQuery SQL statement

- marconi-core/test/Marconi/CoreSpec.hs
* Use a non-empty temp directory prefix. This is a guess at a fix for a somewhat rare failure on darwin, from the socket path not being found in `propWithStreamSocket` from `marconi-core-test`.
* Reports the socket path on failure -- swallowing the original exception and failing the test after reporting the socket path. See the code note on this workaround.
The second item is to help find a real fix for this intermittent problem if needed. See PLT-9260.
- Branch
- PR
> PLT-9261 possible fix and debug for intermittent darwin failure

- marconi-core/test/Marconi/CoreSpec.hs
This is another guess at a "fix" for intermittent failures on Darwin for the named test. The proposed "fix" is based on previous error messages. But it is difficult to analyze, so we might need to do another round to fix the problem for good.
- Branch
- PR
> PLT-9260 Intermittent withStreamSocket test failures
