- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- .github/workflows/pre-commit-check.yml
These settings come partly from `plutus-apps`.
> Add Github basic workflows and PR template

- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Mockchain.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-sidechain/README.md
- marconi-sidechain/marconi-sidechain.cabal
- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/MintBurn.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Types.hs
- marconi-sidechain/src/Marconi/Sidechain/Bootstrap.hs
- marconi-sidechain/test/Spec.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/MintBurn.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Routes.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/RpcClientAction.hs
> PLT-1480 mint-burn endpoint for Marconi-sidechain

- doc/expose-cardano-db-sync-socket.md
Simple documentation clarifications.
I tried the new instructions on my computer, and they work.
- Branch
- PR
> Clarified instructions on exposing node socket file from cardano-db-sync node docker container

- marconi-chain-index/bench/BenchQueries.hs
- marconi-chain-index/src/Marconi/ChainIndex/Error.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
- marconi-sidechain/examples/json-rpc-client/src/Main.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Routes.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/RpcClientAction.hs
PLT-5566, add lower bound slotNo to utxo queries
- Branch
- PR
> add lower bound slot to utxo by address query

- CONTRIBUTING.adoc
- marconi-chain-index/json-rpc/src/Network/JsonRpc/Client/Types.hs
- marconi-chain-index/json-rpc/src/Network/JsonRpc/Server/Types.hs
- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test-lib/Helpers.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-core/src/Marconi/Core/Experiment/Class.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/MixedIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Query.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/Class.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/IndexWrapper.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithAggregate.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithTransform.hs
- marconi-core/src/Marconi/Core/Storable.hs
- marconi-core/src/Marconi/Core/TracedStorable.hs
- marconi-sidechain/marconi-sidechain.cabal
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- nix/cells/marconi/library/ghc-compiler-nix-name.nix
- nix/cells/marconi/library/haskell-language-server-project.nix
* Fixed compilation errors after updating GHC version
* Modified CONTRIBUTING for instructions on how to update GHC versions
- Branch
- PR
> Upgrade GHC from 8.10.7 to 9.2.7

- README.adoc
- nix/cells/marconi/devshells/marconi-shell.nix
- nix/cells/marconi/library/cardano-node.nix
- nix/cells/marconi/packages/cardano-wallet.nix
- nix/cells/marconi/packages/default.nix
This reverts commit 29d2e13d529e9125495f74904dabd76d5ce6f670.
I accidentally forced merged it.
- Branch
- PR
> Revert "Updated cardano-node executable provided by Nix shell to 8.0.0 (#45)"

- doc/read-the-docs-site/adr/0001-record-architecture-decisions.rst
- doc/read-the-docs-site/adr/0002-marconi-initiative.rst
- doc/read-the-docs-site/adr/0003-marconi-indexer-rollbacks.rst
- doc/read-the-docs-site/adr/0004-marconi-query-interface.rst
- doc/read-the-docs-site/adr/0005-marconi-indexers-query-synchronisation-primitive.rst
- doc/read-the-docs-site/adr/index.rst
- doc/read-the-docs-site/index.rst
Haven't changed the content.
I simply changed the ADR numbers.
- Branch
- PR
> Add unmodified Marconi-related ADRs from plutus-apps

- marconi-sidechain/doc/API.adoc
* Did some rewrite in the API.adoc in order to reduce the JSON-Schema duplication across JSON-RPC methods
* Documented the pre-conditions and JSON-RPC error object for each endpoint. Basically, what are the failing scenarios when calling an endpoint?
- Branch
- PR
> Defined pre-conditions and error messages for the marconi-sidechain JSON-RPC API specification

- STYLEGUIDE.adoc
> Add styleguide

- marconi-chain-index/README_alpha-release.md
- marconi-chain-index/app/Main.hs
- marconi-chain-index/src/Marconi/ChainIndex/CLI.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-chain-index/test/Spec/Golden/Cli/marconi-chain-index___disable_address_data.help
- marconi-chain-index/test/Spec/Golden/Cli/marconi-chain-index___help.help
- marconi-chain-index/test/Spec/Marconi/ChainIndex/CLI.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-sidechain/app/Main.hs
- marconi-sidechain/examples/json-rpc-server/src/Main.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/MintBurn.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Types.hs
- marconi-sidechain/src/Marconi/Sidechain/Bootstrap.hs
- marconi-sidechain/src/Marconi/Sidechain/CLI.hs
- marconi-sidechain/test/Spec.hs
- marconi-sidechain/test/Spec/Golden/Cli/marconi-sidechain___help.help
- marconi-sidechain/test/Spec/Golden/Cli/marconi-sidechain___socket.help
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/MintBurn.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
Add a `--match-asset-id` option to `marconi-chain-index` and `marconi-sidechain`.
An asset is defined by it's policy id and (optionally) by its asset name.
- Branch
- PR
> PLT-1364 Filter per token

- marconi-chain-index/marconi-chain-index.cabal
- marconi-sidechain/marconi-sidechain.cabal
Add multithreading support to marconi-chain-index and marconi-sidechain...
- Branch
- PR
> True multiple threads

- marconi-chain-index/src/Marconi/ChainIndex/CLI.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/CLI.hs
Replace "error" with an opt-parse failure.
- Branch
- PR
> PLT-6241 marconi unhandled exception on address filter

- marconi-sidechain/doc/API.adoc
minor clarification
- Branch
- PR
> Minor clarification in API.adoc

- marconi-chain-index/src/Marconi/ChainIndex/CLI.hs
- marconi-chain-index/test/Spec.hs
- marconi-chain-index/test/Spec/Golden/Cli/marconi-chain-index___help.help
- marconi-sidechain/doc/API.adoc
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- marconi-sidechain/test/Spec/Golden/Cli/marconi-sidechain___help.help
> Quickfixes to the marconi-sidechain API following some discussions

- cabal.project
- marconi-chain-index/app/Experimental.hs
- marconi-chain-index/app/Main.hs
- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/CLI.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Utils.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/CLI.hs
- marconi-core/src/Marconi/Core/Experiment/Type.hs
- marconi-sidechain/examples/json-rpc-server/src/Main.hs
- marconi-sidechain/src/Marconi/Sidechain/CLI.hs
- marconi-tutorial/LICENSE
- marconi-tutorial/NOTICE
- marconi-tutorial/app/Main.hs
- marconi-tutorial/marconi-tutorial.cabal
- marconi-tutorial/src/Marconi/Tutorial/CLI.hs
- marconi-tutorial/src/Marconi/Tutorial/HttpServer.hs
- marconi-tutorial/src/Marconi/Tutorial/Indexers.hs
- marconi-tutorial/src/Marconi/Tutorial/Indexers/AddressCount.hs
- marconi-tutorial/src/Marconi/Tutorial/Run.hs
- marconi-tutorial/test/Driver.hs
- marconi-tutorial/test/Spec/Marconi/Tutorial/AddressCount.hs
- nix/haskell-project.nix
* Provide a simple AddressCount indexer with the new Marconi API
* Tutorial is an executable which starts the indexing with an HTTP server (which doesn't actually return the query result of the indexer for now)
* Renamed functions in Marconi.ChainIndex.CLI with more significant names
* Refactored the marconi-chain-index experimental main application
- Branch
- PR
> Boostrap marconi-tutorial package

- cabal.project
- cardano-streaming/cardano-streaming.cabal
- cardano-streaming/src/Cardano/Streaming.hs
- cardano-streaming/src/Cardano/Streaming/Helpers.hs
- flake.lock
- flake.nix
- marconi-chain-index/bench/BenchQueries.hs
- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Node/Client/GenesisConfig.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Mockchain.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Types.hs
- marconi-chain-index/test-lib/Helpers.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/AddressDatum/Generators.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/EpochState.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/ScriptTx.hs
- marconi-sidechain/README.md
- marconi-sidechain/marconi-sidechain.cabal
- nix/haskell-project.nix
- nix/shell.nix
* updated index-state of hackage and CHaP
* updated the iohk-nix flake dependency in order to have access to the new blst library when building core components
* removed cardano-testnet from marconi-chain-index because there is only an out-of-date version in CHaP. We will plan to replace it with cardano-node-emulator so it's okay.
- Branch
- PR
> Updated cardano-api to 8.8, cardano-cli to 8.3.1.0 and cardano-node to 8.1.1

- marconi-sidechain/README.md
Fix a broken link
- Branch
- PR
> Small doc fix

- marconi-chain-index/app/Experimental.hs
- marconi-chain-index/src/Marconi/ChainIndex/Error.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/AddressDatum.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/EpochState.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/ScriptTx.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Utils.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/MintBurn.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Types.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/MintBurn.hs
- marconi-tutorial/src/Marconi/Tutorial/Indexers.hs
- Add specific error messages for the getBurnTokenEvent JSON-RPC endpoint.
- Restructure the Marconi-chain-index errors to introduce indexer specific errors.
- Branch
- PR
> PLT-6210 JSON error for the mint-burn indexer

- benchmark/README.md
- benchmark/marconi-dashboard.json
- doc/read-the-docs-site/adr/0007-observability.rst
- doc/read-the-docs-site/adr/index.rst
- flake.lock
- flake.nix
- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-sidechain/examples/run-pre-prod-queries
- marconi-sidechain/marconi-sidechain.cabal
- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- nix/scripts/start-benchmarking-machine.nix
- nix/shell.nix
* Added draft ADR for how we observe the runtime behaviour of Marconi
* Added script in Nix shell (disabled by default) which starts a VM
running Grafana and Prometheus
- Branch
- PR
> ADR on marconi observability

- cabal.project
In a hurry of fixing the last sidechain bug, I push a broken WIP instead of the right branch. I'm reverting it.
- Branch
- PR
> Remove inexisting component

- marconi-chain-index/bench/BenchQueries.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Orphans.hs
- marconi-sidechain/doc/API.adoc
- marconi-sidechain/examples/json-rpc-client/src/Main.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Routes.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/RpcClientAction.hs
* Make upper bound slot of getUtxosFromAddress optional
* Change the Interval representation in the Utxo indexer
- Branch
- PR
> Update marconi-sidechain API spec

- marconi-chain-index/src/Marconi/ChainIndex/Error.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/EpochState.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/MintBurn.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Types.hs
The SQL errors that are raised when we query an indexer are forwarded with a specific JSON-RPC error code.
- Branch
- PR
> PLT-6281 Specific error messages for Internal error

- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/EpochState.hs
- marconi-chain-index/src/Marconi/ChainIndex/Utils.hs
* Removed the node tip block number in the LedgerState filename stored on disk
* Use only the LedgerState filenames resumable points instead of the points stored on the database for the EpochSDD and EpochNonce tables.
* When starting the application, query the current node tip and pass that info on each indexer. That info is necessary for EpochState indexer in order to remove old LedgerStates that have become immutable.
* Initially, we only stored immutable LedgerState at the beginning of each epoch. Now, we also store the immutable LedgerState right before a rollbackable point. This capability allows us to resume to a point closer to the tip when almost fully synced.
- Branch
- PR
> PLT-6559 Fixed bug in EpochState indexer

- doc/read-the-docs-site/adr/0006-indexer-resuming-strategy.rst
> PLT-6816 Change decision of Marconi resuming ADR with new implementation

- config/cardano-node/preprod/preprod-topology.json
- flake.lock
- marconi-chain-index/app/Experimental.hs
- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/SQLiteIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Worker.hs
Did not migrate the Query interface, nor the tests. They will be migrated in a future PR.
- Branch
- PR
> Rewrote the indexing part of the MintBurn indexer with new Marconi API.

- marconi-sidechain/doc/API.adoc
Moved some pre-conditions as post-conditions in the marconi-sidechain API doc for the EpochState-related methods.
- Branch
- PR
> Moved some pre-conditions as post-conditions in marconi-sidechain API doc

- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/BlockInfo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/BlockInfo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/Spent.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/SQLiteIndexer.hs
> Small fixes to the BlockInfo indexer.

- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/UtxoQuery.hs
- marconi-core/marconi-core.cabal
- marconi-core/src/Marconi/Core/Experiment.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/MixedIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/SQLiteAggregateQuery.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/SQLiteIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/IndexTransformer.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithAggregate.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithCache.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithCatchup.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithDelay.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithPruning.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithTracer.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithTransform.hs
- marconi-core/src/Marconi/Core/Experiment/Worker.hs
- marconi-core/test/Marconi/Core/Spec/Experiment.hs
- marconi-core/test/Spec.hs
Document and move IndexWrapper to IndexTransformer.
- Branch
- PR
> More documentation

- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Worker.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Run.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Types.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/SQLiteIndexer.hs
- marconi-core/src/Marconi/Core/Experiment/Type.hs
- marconi-core/test/Marconi/Core/Spec/TracedSqlite.hs
Migrated MintBurn queries and tests to the new marconi-core APIAPI. The indexer was renamed to MintTokenEvent.
- Branch
- PR
> PLT-7082 Migrated MintBurn queries and tests to the new marconi-core API

- marconi-core/marconi-core.cabal
- marconi-core/src/Marconi/Core/Experiment.hs
- marconi-core/src/Marconi/Core/Experiment/Transformer/WithResume.hs
- marconi-core/src/Marconi/Core/Experiment/Type.hs
- marconi-core/test/Marconi/Core/Spec/Experiment.hs
- marconi-core/test/Spec.hs
Resuming transformer for the new indexers, following the latest ADR.
It lacks tests, they will be added later.
- Branch
- PR
> PLT-6760 New indexer resume

- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/test-compare-cardano-db-sync/Spec.hs
- nix/cabal-project.nix
* Made the tests build in CI, but won't be executed in CI
* Fixed compilation errors
- Branch
- PR
> Fixed compilation errors of cardano-db-sync comparison tests

- marconi-chain-index/src/Marconi/ChainIndex/Node/Client/Retry.hs
- marconi-chain-index/src/Marconi/ChainIndex/Orphans.hs
- marconi-chain-index/src/Marconi/ChainIndex/Types.hs
- marconi-sidechain/doc/API.adoc
- marconi-sidechain/marconi-sidechain.cabal
- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- marconi-sidechain/src/Marconi/Sidechain/Bootstrap.hs
- marconi-sidechain/src/Marconi/Sidechain/CLI.hs
- marconi-sidechain/src/Marconi/Sidechain/Env.hs
- marconi-sidechain/src/Marconi/Sidechain/Run.hs
- marconi-sidechain/test/Spec.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Env.hs
This implements:
* Tracing the `CliArgs` on startup
* Add `Trace` and `CliArgs` to `SidechainEnv`
* Add basic tests for `SidechainEnv`
* Add some use of `ReaderT`
* Add a `/params` API endpoint
- Branch
- PR
> PLT-634 Trace CLI args

- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
- marconi-sidechain/src/Marconi/Sidechain/Bootstrap.hs
- marconi-sidechain/test/Spec.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/RpcClientAction.hs
Also tidy up `marconi-sidechain/src/Marconi/Sidechain/Bootstrap.hs` a bit
- Branch
- PR
> PLT-7446 Finish refactoring marconi-sidechain to use ReaderT SidechainEnv

- marconi-chain-index/src/Marconi/ChainIndex/CLI.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/CLIInputValidation/Golden/invalidAssetId-assetName-invalidBase16Format.golden
- marconi-sidechain/test/Spec/Marconi/Sidechain/CLIInputValidation/Golden/invalidAssetId-assetName-invalidBase16Length.golden
- marconi-sidechain/test/Spec/Marconi/Sidechain/CLIInputValidation/Golden/invalidAssetId-assetName-tooLong.golden
- marconi-sidechain/test/Spec/Marconi/Sidechain/CLIInputValidation/Golden/invalidAssetId-policyId-1ByteLong.golden
- marconi-sidechain/test/Spec/Marconi/Sidechain/CLIInputValidation/Golden/invalidAssetId-policyId-1ByteShort.golden
- marconi-sidechain/test/Spec/Marconi/Sidechain/CLIInputValidation/Golden/invalidAssetId-policyId-1HexCharLong.golden
- marconi-sidechain/test/Spec/Marconi/Sidechain/CLIInputValidation/Golden/invalidAssetId-policyId-1HexCharShort.golden
- marconi-sidechain/test/Spec/Marconi/Sidechain/CLIInputValidation/Golden/invalidAssetId-policyId-badBase16Format.golden
> PLT-7086 Improve error reporting for incorrect --match-asset-id values

- marconi-sidechain/examples/run-pre-prod-queries
The current script is very repetitive and the output is hard to read. This creates shell functions for banners and queries, and shows the inputs in a better way, by including just the method name and the params, and formatting the params with `jq`. The query logging now looks like this:
```
getBurnTokenEvents({
"policyId": "e222ae950cef1915dcb9db8840dc9c3df3785f9a10eca30dfb84ad40",
"afterTx": "0a872c4fcf87f041caab5d5ecaeae19fd0e26de14241167c8dee7d1b26b5b4f7"
}) =
{
"id": 1,
"jsonrpc": "2.0",
"result": [
{
"assetName": "",
"blockHeaderHash": "0c75f6830f5f20a066d6a29aa0e6e25c7272de5066024f61b207ffad9494cc2d",
"blockNo": 191108,
"burnAmount": 10000000,
...
```
- Branch
- PR
> PLT-7495 Refactor `marconi-sidechain/examples/run-pre-prod-queries`

- marconi-sidechain/marconi-sidechain.cabal
- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
Log http requests using the logger provided in `wai-extra` for formatting but using our logging framework for the output. Log at _debug_ level.
- Branch
- PR
> PLT-7495 Add request logging to `marconi-sidechain` http server

- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Routes/Golden/address-utxo-response.json
- marconi-sidechain/test/Spec/Marconi/Sidechain/Routes.hs
> Add EpochNo to the getUtxoByAddress queries

- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/CLI.hs
- marconi-chain-index/src/Marconi/ChainIndex/Types.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
* Converted TargetAddresses from non-empty list to non-empty set
* Removed uniqueness-ensuring logic when parsing addresses. It's made redundant by the `List -> Set` transformation.
* Fixed a small typo in an edited comment ("compat`a`ble" -> "compat`i`ble")
- Branch
- PR
> PLT-1563 - TargetAddresses are now a non-empty set, rather than non-empty list

- marconi-sidechain/marconi-sidechain.cabal
> Depend on marconi-sidechain exe for tests

- marconi-chain-index/bench/BenchQueries.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Run.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Runner.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Run.hs
- marconi-chain-index/src/Marconi/ChainIndex/Types.hs
- marconi-sidechain/src/Marconi/Sidechain/Bootstrap.hs
- marconi-tutorial/src/Marconi/Tutorial/Indexers.hs
* Added a new data type for common args/configuration between experimental and legacy `runIndexer`/`runIndexers` functions
* Small refactor to allow `SecurityParam` to be passed into legacy `runIndexers`, rather than calculated within it
- Branch
- PR
> PLT-6869 - Run Indexers Config

- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Run.hs
- marconi-core/src/Marconi/Core/Experiment/Indexer/SQLiteIndexer.hs
- marconi-tutorial/marconi-tutorial.cabal
- marconi-tutorial/src/Marconi/Tutorial/Env.hs
- marconi-tutorial/src/Marconi/Tutorial/HttpServer.hs
- marconi-tutorial/src/Marconi/Tutorial/Indexers.hs
- marconi-tutorial/src/Marconi/Tutorial/Indexers/AddressCount.hs
- marconi-tutorial/src/Marconi/Tutorial/Run.hs
* Added resuming capabilities
* Used ReaderT pattern and Env type to share types between indexing thread and query thread. Used an IORef to share the MVar between the query thread and the indexer thread.
* Completed link of JSON-RPC server to indexer thread.
* Started experimenting with typeclass to convert a Queryable to a Servant Handler.
- Branch
- PR
> Updated marconi-tutorial with additional features

- cabal.project
> Update index-state of hackage and CHaP

- marconi-chain-index/src/Marconi/ChainIndex/Types.hs
RunIndexerConfig is now a record, and lenses are generated for it.
- Branch
- PR
> PLT-7815 - Made RunIndexerConfig a lensy record

- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Spent.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Experimental/Run.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs
- marconi-core/marconi-core.cabal
- marconi-core/src/Marconi/Core.hs
- marconi-core/src/Marconi/Core/Transformer/WithCatchup.hs
- marconi-core/src/Marconi/Core/Transformer/WithCatchup/SQLite.hs
- marconi-core/test/Marconi/CoreSpec.hs
- marconi-tutorial/src/Marconi/Tutorial/Indexers/AddressCount.hs
> PLT-6359 Create SQL index tables only once fully synced

- marconi-sidechain/src/Marconi/Sidechain/Error.hs
Changed the exit code when receiving a TimedOut exception from 124 to 142, as per Neil's suggestion in the comments of https://input-output.atlassian.net/browse/PLT-7045
- Branch
- PR
> Made TimedOut exit code 142, in line with Neil's suggestion

- README.adoc
Simple README changes as discussed with @berewt 
- Branch
- PR
> Better outline of README

- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/Orphans.hs
- marconi-chain-index/src/Marconi/ChainIndex/Utils.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Indexers/MintBurn.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Mockchain.hs
- marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Types.hs
- marconi-chain-index/test-lib/Helpers.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/AddressDatum/Generators.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/EpochState.hs
- marconi-sidechain-node/marconi-sidechain-node/marconi-sidechain-node.cabal
- marconi-sidechain/marconi-sidechain.cabal
Most of the changes are in the tests, and almost all are to do with the API switching from `ProtocolParams` to `LedgerProtocolParams`.
I'm not sure about the changes in the final commit. Without these `propGetTxBodyScriptsRoundtrip` fails with an `ErrorCall` exception coming from `Cardano.Api.ProtocolParameters.fromtoShelleyPParams` from the two `PpceMissingParameter` errors. I hacked a solution to get tests to pass, but we should talk about it, I think. 
- Branch
- PR
> PLT-7795 Upgrade to cardano-api 8.20

- cabal.project
- legacy/marconi-chain-index-legacy/marconi-chain-index-legacy.cabal
- legacy/marconi-chain-index-legacy/test-lib/Gen/Marconi/ChainIndex/Legacy/Indexers/MintBurn.hs
- legacy/marconi-chain-index-legacy/test-lib/Helpers.hs
- legacy/marconi-chain-index-legacy/test/Spec/Marconi/ChainIndex/Legacy/Indexers/EpochState.hs
- legacy/marconi-chain-index-legacy/test/Spec/Marconi/ChainIndex/Legacy/Indexers/MintBurn.hs
- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/test-lib/Helpers.hs
> PLT-6604: Run MintBurn e2e test with cardano-node-socket-emulator

- marconi-chain-index/src/Marconi/ChainIndex/Run.hs
- marconi-sidechain/src/Marconi/Sidechain/Run.hs
As discussed in today's grooming session.
- Branch
- PR
> PLT-8135 Avoid showing log messages in help output

- marconi-sidechain-node/cabal.project
- marconi-sidechain-node/flake.lock
- marconi-sidechain-node/flake.nix
- marconi-sidechain-node/marconi-sidechain-node/marconi-sidechain-node.cabal
- marconi-sidechain-node/marconi-sidechain-node/src/Marconi/Sidechain/Node/Run.hs
- marconi-sidechain-node/nix/project.nix
> PLT-7977 marconi-sidechain-node: Upgrade to cardano-node 8.4.0-pre

- doc/read-the-docs-site/architecture/index.rst
- doc/read-the-docs-site/architecture/marconi-core-building-blocks.rst
- doc/read-the-docs-site/architecture/runtime-view.rst
- doc/read-the-docs-site/architecture/sequence-diagram.rst
> Add Marconi runtime view in documentation

- legacy/marconi-chain-index-legacy/src/Marconi/ChainIndex/Legacy/Indexers/Utxo.hs
- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/Api/JsonRpc/Endpoint/Utxo.hs
- marconi-chain-index/src/Marconi/ChainIndex/Api/JsonRpc/Endpoint/Utxo/SpentInfoResult.hs
- marconi-chain-index/src/Marconi/ChainIndex/Api/JsonRpc/Endpoint/Utxo/Types.hs
- marconi-chain-index/src/Marconi/ChainIndex/Api/JsonRpc/Endpoint/Utxo/Wrappers.hs
- marconi-chain-index/src/Marconi/ChainIndex/Api/JsonRpc/Routes.hs
- marconi-chain-index/src/Marconi/ChainIndex/Api/JsonRpc/Server.hs
- marconi-chain-index/src/Marconi/ChainIndex/CLI.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/UtxoQuery.hs
- marconi-chain-index/test/Spec/Golden/Cli/marconi-chain-index___help.help
- marconi-chain-index/test/Spec/Golden/Routes/address-utxo-response.json
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Api/Routes.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/UtxoQuery.hs
- marconi-core-json-rpc/src/Marconi/Core/JsonRpc.hs
- marconi-core/src/Marconi/Core/Indexer/SQLiteAggregateQuery.hs
* Added machinery which allows us to use `MonadError` in `SQLiteAggregateQuery` `Queryable` instances (even though I'm not using it for this)
* Added a `getUtxosFromAddress` endpoint
* Fixed a typo in `--help` output
* Added golden tests for the new endpoint
- Branch
- PR
> PLT-8077 - utxo endpoint

- cabal.project
> Fix hash of cardano-node-emulator dependency

- nix/shell.nix
Add ghcid and hoogle to nix-shell. No test is provided. Acceptance criteria is outlined in the corresponding ticket:
[PLT-9038](https://input-output.atlassian.net/browse/PLT-8907)
- Branch
- [ X] Commit sequence broadly makes sense and have useful messages
- [ X] Relevant tickets are mentioned in commit messages
- PR
> Add ghcid to nix shell

- README.adoc
- doc/read-the-docs-site/adr/0002-indexer-resuming-strategy.rst
- doc/read-the-docs-site/architecture/comparison-other-chain-indexing-projects.rst
- marconi-core/README.md
- Update the ADR with the latest decision about resuming
- Create a comparison between marconi and the other indexers
- Add key features to the readme
- Update the package list in the readme
- Branch
- PR
> PLT-7926 document resuming and some extras

- marconi-cardano-core/src/Marconi/Cardano/Core/Types.hs
> Remove RunIndexerConfig from Marconi.Cardano.Core.Types

- doc/read-the-docs-site/architecture/marconi-core-building-blocks.rst
- marconi-cardano-core/src/Marconi/Cardano/Core/Extract/WithDistance.hs
- marconi-core/src/Marconi/Core/Worker.hs
Just a few Minor documentation typo fixes
[PLT-7891]
- Branch
- PR
> minor  documentation typo fixes
